In [1]:
import pandas as pd
import numpy as np 

In [2]:
df = pd.read_csv('spam.csv', encoding = "ISO-8859-1")
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [4]:
df.v1.value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df['spam'] = df['v1'].apply(lambda x: 1 if x=='spam' else 0)

In [6]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  spam  
0        NaN        NaN     0  
1        NaN        NaN     0  
2        NaN        NaN     1  
3        NaN        NaN     0  
4        NaN        NaN     0

In [7]:
from sklearn.model_selection import train_test_split #balanced imbalance data
X_train, X_test, y_train, y_test = train_test_split(df.v2, df.spam, test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [9]:
X_test.shape

(1115,)

In [10]:
type(X_train)

pandas.core.series.Series

In [11]:
X_train[:4]

5540    ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...
3253               I can make lasagna for you... vodka...
4770                             Hi..i got the money da:)
2465                       S.i think he is waste for rr..
Name: v2, dtype: object

In [13]:
X_train[:4][5540]

'ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE MINS. INDIA CUST SERVs SED YES. L8ER GOT MEGA BILL. 3 DONT GIV A SHIT. BAILIFF DUE IN DAYS. I O å£250 3 WANT å£800'

In [14]:
y_train[:4]

5540    1
3253    0
4770    0
2465    0
Name: spam, dtype: int64

In [15]:
type(X_train.values)

numpy.ndarray

In [16]:
X_train.values

array(['ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE MINS. INDIA CUST SERVs SED YES. L8ER GOT MEGA BILL. 3 DONT GIV A SHIT. BAILIFF DUE IN DAYS. I O å£250 3 WANT å£800',
       'I can make lasagna for you... vodka...',
       'Hi..i got the money da:)', ...,
       'Double Mins & Double Txt & 1/2 price Linerental on Latest Orange Bluetooth mobiles. Call MobileUpd8 for the very latest offers. 08000839402 or call2optout/LF56',
       'K k pa Had your lunch aha.',
       'U having lunch alone? I now so bored...'], dtype=object)

In [18]:
X_train.values[0]

'ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE MINS. INDIA CUST SERVs SED YES. L8ER GOT MEGA BILL. 3 DONT GIV A SHIT. BAILIFF DUE IN DAYS. I O å£250 3 WANT å£800'

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()

In [21]:
X_train_cv =  v.fit_transform(X_train.values)  #it creates bag of words
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58887 stored elements and shape (4457, 7731)>

In [22]:
X_train_cv.toarray()[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
X_train_cv.toarray()[0]


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
X_train_cv.shape #4457 no of email each is a vector of  size 7757

(4457, 7731)

In [25]:
v.get_feature_names_out() #vocabulary

array(['00', '000', '000pes', ..., 'ûïharry', 'ûò', 'ûówell'],
      dtype=object)

In [26]:
v.get_feature_names_out().shape #no of words in vocabulary


(7731,)

In [27]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [28]:
v.vocabulary_ # word: index

{'asked': 1069,
 '3mobile': 454,
 'if': 3570,
 '0870': 69,
 'chatlines': 1707,
 'inclu': 3614,
 'in': 3608,
 'free': 2958,
 'mins': 4474,
 'india': 3629,
 'cust': 2089,
 'servs': 5992,
 'sed': 5943,
 'yes': 7661,
 'l8er': 3959,
 'got': 3173,
 'mega': 4403,
 'bill': 1317,
 'dont': 2377,
 'giv': 3117,
 'shit': 6050,
 'bailiff': 1176,
 'due': 2455,
 'days': 2144,
 '250': 360,
 'want': 7349,
 '800': 620,
 'can': 1593,
 'make': 4300,
 'lasagna': 4003,
 'for': 2915,
 'you': 7677,
 'vodka': 7286,
 'hi': 3394,
 'the': 6785,
 'money': 4545,
 'da': 2108,
 'think': 6816,
 'he': 3334,
 'is': 3717,
 'waste': 7365,
 'rr': 5796,
 'told': 6924,
 'that': 6781,
 'am': 909,
 'coming': 1881,
 'on': 4901,
 'wednesday': 7403,
 'thanks': 6773,
 'being': 1275,
 'there': 6802,
 'me': 4381,
 'just': 3849,
 'to': 6907,
 'talk': 6670,
 'saturday': 5878,
 'are': 1021,
 'very': 7242,
 'dear': 2155,
 'cherish': 1731,
 'having': 3330,
 'as': 1058,
 'brother': 1487,
 'and': 934,
 'role': 5773,
 'model': 4529,
 'privat

In [ ]:
v.vocabulary

In [29]:
X_train_np = X_train_cv.toarray()

In [30]:
X_train_np[0] #first mail vector with word frequency

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
np.where(X_train_np[0] != 0) #non zero vector where word index exist in first email

(array([  69,  360,  454,  620, 1069, 1176, 1317, 1707, 2089, 2144, 2377,
        2455, 2958, 3117, 3173, 3570, 3608, 3614, 3629, 3959, 4403, 4474,
        5943, 5992, 6050, 7349, 7661], dtype=int64),)

In [32]:
X_train_np[0][69] #word frequency ie 'and' index 980 in first email 

1

In [33]:
v.get_feature_names_out()[69] #word index

'0870'

In [34]:
v.get_feature_names_out()[1]


'000'

In [35]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [36]:
model.fit(X_train_cv, y_train) #model is trained

MultinomialNB()

In [37]:
X_test_cv = v.transform(X_test.values) #count vectorized at the time of X_test transform only transform() is used not fit_transform()

In [38]:
X_test_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 14014 stored elements and shape (1115, 7731)>

In [39]:
X_test_cv.shape

(1115, 7731)

In [40]:
from sklearn.metrics import classification_report #it is used becouse ham and spam are imbalanced if balanced then used accuracy score

In [41]:
y_pred = model.predict(X_test_cv)

In [43]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       954
           1       0.97      0.95      0.96       161

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [44]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [45]:
from sklearn.pipeline import Pipeline

In [47]:
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb', MultinomialNB())
]) 

In [48]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [49]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       954
           1       0.97      0.95      0.96       161

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

